[package]
name = "libdeflate-sys"
version = "0.1.0"
authors = ["Adam Kewley <contact@adamkewley.com>"]
edition = "2018"
build = "build.rs"
license = "Apache-2.0"
repository = "https://github.com/adamkewley/libdeflate-sys"
description = """
Bindings to the system libdeflate library
"""
categories = ["external-ffi-bindings"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
bindgen = "0.50"
cc = "1.0"
