[package]
name = "libdeflater"
version = "0.1.0"
authors = ["Adam Kewley <contact@adamkewley.com>"]
edition = "2018"
build = "build.rs"
license = "Apache-2.0"
repository = "https://github.com/adamkewley/libdeflater"
description = """
Rust bindings for libdeflate
"""
categories = ["external-ffi-bindings"]

[build-dependencies]
bindgen = "0.50"
cc = "1.0"

[dev-dependencies]
criterion = "0.3"
flate2 = "0.2.5"
serde = { version = "1.0.101", features = ["derive"] }
toml = "0.5.3"

[[bench]]
name = "benchmarks"
harness = false
