# custom benchmarks to run.
#
# The performance of compressing entries here will be directly
# compared to a basic use of the flate2 api for
# comparison. Decompression performance is benchmarked by first
# compressing the entry with flate2 then decompressing it with
# flate2/libdeflate multiple times to measure performance.
#
# The data associated with entries here typically isn't in the repo
# (they're binaries).


# These entries were downloaded from
# http://www.data-compression.info/files/corpora/largecalgarycorpus.zip
# (md5: e2b9cfb9c0e2949944057475be65fb84) and unpacked to `bench_data`
# in project dir

[bib]
path = "bench_data/bib"
description = 'ASCII text in UNIX "refer" format – 725 bibliographic references.'

[book1]
path = "bench_data/book1"
description = "unformatted ASCII text – Thomas Hardy: Far from the Madding Crowd."

[book2]
path = "bench_data/book2"
description = 'ASCII text in UNIX "troff" format – Witten: Principles of Computer Speech.'

[geo]
path = "bench_data/geo"
description = "32 bit numbers in IBM floating point format – seismic data"

[news]
path = "bench_data/news"
description = "ASCII text – USENET batch file on a variety of topics."

[obj1]
path = "bench_data/obj1"
description = "VAX executable program – compilation of PROGP."

[obj2]
path = "bench_data/obj2"
description = 'Macintosh executable program – "Knowledge Support System".'

[paper1]
path = "bench_data/paper1"
description = 'UNIX "troff" format – Witten, Neal, Cleary: Arithmetic Coding for Data Compression.'

[paper2]
path = "bench_data/paper2"
description = 'UNIX "troff" format – Witten: Computer (in)security.'

[pic]
path = "bench_data/pic"
description = "1728 x 2376 bitmap image (MSB first): text in French and line diagrams."

[progc]
path = "bench_data/progc"
description = "Source code in C – UNIX compress v4.0."

[progl]
path = "bench_data/progl"
description = "Source code in Lisp – system software."

[progp]
path = "bench_data/progp"
description = "Source code in Pascal – program to evaluate PPM compression."

[trans]
path = "bench_data/trans"
description = "ASCII and control characters – transcript of a terminal session."
